# Generated by Django 5.1.4 on 2024-12-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_friendlist_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='invitePending',
            field=models.BooleanField(default=True),
        ),
    ]
